# Generated by Django 2.0.4 on 2018-04-20 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='ApiBlog',
        ),
    ]
