# Generated by Django 2.0.4 on 2018-04-20 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180420_0413'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApiBlog',
        ),
    ]
